---
name: Development build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: --timeout=3m

      - name: Download go dependencies
        run: go mod download

      - name: Run build
        run: go build -o webhook

      - name: Build Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:latest
